name: null_safe_instagram_image_picker
description: Flutter package to pick images from Instagram gallery
version: 0.0.1
homepage: https://github.com/KashifUmar123/null_safe_instagram_image_picker.git

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: